language: csharp
solution: mruv-pb-csharp.sln
dotnet: 2.2.402

env:
  global:
    - secure: "iDj/TnJCmpBW2z1FL7ikl4JNKMKicovw4YUg71euuaodBMxnFdWt1ChWnBB5ZoMgYWptuOUfcv8yGOzDGEz930JK3aYo7rVVzpKGBXdgK0cSHEuTUfCfH0XE9x3qc7EvG9LetkFA0EmfiZ3VQPMAc+cpDmrK/0ZeKsiflUbaYmmaFzszTCPgG5OyLiPgggGSsXdaWYu9jEmPLv6L0kyktDwhBeHvT298CqXp6yhEzXAUtM8aLoeQnYhwXxRdF4iNeWfShN9nwSx3NU96PUSueybG786smlly1/VEgcRftnQQwgXZowyPDxkRcn8cXPyVsYpSYNlWV7i6GUhcy7gjAigRal2Lub2B5bQ1oVhRi71Dp6O+vyIltMI4L1fYIbXU4rbopvOxne68gKA4EK66c7BI553NqXM8EuP+G6UDrnxD2fWyt2gOG2yVEYj5ofzuxwAEKfz0IpQ+sJS/gTz81pG+yQmSHJuupzyrZiLiQlfhssJTNJaSEU78VEt/s1tw03wFcWPzWk9R4YV3nJwbVbBiJdnmi7tq9xZex/Jzwj0opglUYgdnmTLEPrkoPZuWvzocNH+PQIMlnQ+ZKNrZYxgG90ZGnRBvt76o3WZFN6V/ePLko/LezimoVAbkRwvne2FZp1EmwK9AH2d2AX2WBJ2hu4UXYWUtwqsII6qn5GI="

install:
  - dotnet restore

script:
  - dotnet build
  - dotnet test

deploy:
  skip_cleanup: true
  provider: script
  script: dotnet pack -p:PackageVersion=$(git describe --tags) && dotnet nuget push bin/Debug/*.nupkg -k $NUGET_API_KEY -s https://api.nuget.org/v3/index.json
  on:
    branch: master
    tags: true
