// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: objects/models.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Mruv.Objects {

  /// <summary>Holder for reflection information generated from objects/models.proto</summary>
  public static partial class ModelsReflection {

    #region Descriptor
    /// <summary>File descriptor for objects/models.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ModelsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChRvYmplY3RzL21vZGVscy5wcm90bxIMbXJ1di5vYmplY3RzGhxnb29nbGUv",
            "YXBpL2Fubm90YXRpb25zLnByb3RvIqMCCgtPYmplY3RNb2RlbBINCgVtb2Rl",
            "bBgBIAEoBRISCgptb2RlbF9uYW1lGAIgASgJEgwKBG5hbWUYAyABKAkSEAoI",
            "Y2F0ZWdvcnkYBCABKAkSDgoGbGVuZ3RoGAUgASgBEg0KBXdpZHRoGAYgASgB",
            "Eg4KBmhlaWdodBgHIAEoARIMCgRzaXplGAggASgBEgwKBHRhZ3MYCSADKAkS",
            "FQoNaGFzX2NvbGxpc2lvbhgKIAEoCBIVCg1icmVha3Nfb25faGl0GAsgASgI",
            "EhUKDWhhc19hbmltYXRpb24YDCABKAgSFwoPdmlzaWJsZV9ieV90aW1lGBAg",
            "ASgIEhQKDHZpc2libGVfZnJvbRgRIAEoDRISCgp2aXNpYmxlX3RvGBIgASgN",
            "IkoKGENyZWF0ZU9iamVjdE1vZGVsUmVxdWVzdBIuCgtvYmplY3RfdHlwZRgB",
            "IAEoCzIZLm1ydXYub2JqZWN0cy5PYmplY3RNb2RlbCInChlDcmVhdGVPYmpl",
            "Y3RNb2RlbFJlc3BvbnNlEgoKAmlkGAEgASgNIiYKFUdldE9iamVjdE1vZGVs",
            "UmVxdWVzdBINCgVtb2RlbBgBIAEoBSJIChZHZXRPYmplY3RNb2RlbFJlc3Bv",
            "bnNlEi4KC29iamVjdF90eXBlGAEgASgLMhkubXJ1di5vYmplY3RzLk9iamVj",
            "dE1vZGVsIkoKGFVwZGF0ZU9iamVjdE1vZGVsUmVxdWVzdBIuCgtvYmplY3Rf",
            "dHlwZRgBIAEoCzIZLm1ydXYub2JqZWN0cy5PYmplY3RNb2RlbCIbChlVcGRh",
            "dGVPYmplY3RNb2RlbFJlc3BvbnNlIikKGERlbGV0ZU9iamVjdE1vZGVsUmVx",
            "dWVzdBINCgVtb2RlbBgBIAEoBSIbChlEZWxldGVPYmplY3RNb2RlbFJlc3Bv",
            "bnNlIisKFUZldGNoQWxsTW9kZWxzUmVxdWVzdBISCgpjaHVua19zaXplGAEg",
            "ASgNIqQBChZGZXRjaEFsbE1vZGVsc1Jlc3BvbnNlEkAKBm1vZGVscxgBIAMo",
            "CzIwLm1ydXYub2JqZWN0cy5GZXRjaEFsbE1vZGVsc1Jlc3BvbnNlLk1vZGVs",
            "c0VudHJ5GkgKC01vZGVsc0VudHJ5EgsKA2tleRgBIAEoBRIoCgV2YWx1ZRgC",
            "IAEoCzIZLm1ydXYub2JqZWN0cy5PYmplY3RNb2RlbDoCOAEysQUKF01ydVZP",
            "YmplY3RNb2RlbHNTZXJ2aWNlEoABChFDcmVhdGVPYmplY3RNb2RlbBImLm1y",
            "dXYub2JqZWN0cy5DcmVhdGVPYmplY3RNb2RlbFJlcXVlc3QaJy5tcnV2Lm9i",
            "amVjdHMuQ3JlYXRlT2JqZWN0TW9kZWxSZXNwb25zZSIagtPkkwIUIg8vdjEv",
            "b2JqZWN0VHlwZXM6ASoSfAoOR2V0T2JqZWN0TW9kZWwSIy5tcnV2Lm9iamVj",
            "dHMuR2V0T2JqZWN0TW9kZWxSZXF1ZXN0GiQubXJ1di5vYmplY3RzLkdldE9i",
            "amVjdE1vZGVsUmVzcG9uc2UiH4LT5JMCGRIXL3YxL29iamVjdFR5cGVzL3tt",
            "b2RlbH0SlAEKEVVwZGF0ZU9iamVjdE1vZGVsEiYubXJ1di5vYmplY3RzLlVw",
            "ZGF0ZU9iamVjdE1vZGVsUmVxdWVzdBonLm1ydXYub2JqZWN0cy5VcGRhdGVP",
            "YmplY3RNb2RlbFJlc3BvbnNlIi6C0+STAigyIy92MS9vYmplY3RUeXBlcy97",
            "b2JqZWN0X3R5cGUubW9kZWx9OgEqEoUBChFEZWxldGVPYmplY3RNb2RlbBIm",
            "Lm1ydXYub2JqZWN0cy5EZWxldGVPYmplY3RNb2RlbFJlcXVlc3QaJy5tcnV2",
            "Lm9iamVjdHMuRGVsZXRlT2JqZWN0TW9kZWxSZXNwb25zZSIfgtPkkwIZKhcv",
            "djEvb2JqZWN0VHlwZXMve21vZGVsfRJ2Cg5GZXRjaEFsbE1vZGVscxIjLm1y",
            "dXYub2JqZWN0cy5GZXRjaEFsbE1vZGVsc1JlcXVlc3QaJC5tcnV2Lm9iamVj",
            "dHMuRmV0Y2hBbGxNb2RlbHNSZXNwb25zZSIXgtPkkwIREg8vdjEvb2JqZWN0",
            "VHlwZXMwAUInWiVnaXRodWIuY29tL01ydVYtUlAvbXJ1di1wYi1nby9vYmpl",
            "Y3RzYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Api.AnnotationsReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Mruv.Objects.ObjectModel), global::Mruv.Objects.ObjectModel.Parser, new[]{ "Model", "ModelName", "Name", "Category", "Length", "Width", "Height", "Size", "Tags", "HasCollision", "BreaksOnHit", "HasAnimation", "VisibleByTime", "VisibleFrom", "VisibleTo" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Mruv.Objects.CreateObjectModelRequest), global::Mruv.Objects.CreateObjectModelRequest.Parser, new[]{ "ObjectType" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Mruv.Objects.CreateObjectModelResponse), global::Mruv.Objects.CreateObjectModelResponse.Parser, new[]{ "Id" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Mruv.Objects.GetObjectModelRequest), global::Mruv.Objects.GetObjectModelRequest.Parser, new[]{ "Model" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Mruv.Objects.GetObjectModelResponse), global::Mruv.Objects.GetObjectModelResponse.Parser, new[]{ "ObjectType" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Mruv.Objects.UpdateObjectModelRequest), global::Mruv.Objects.UpdateObjectModelRequest.Parser, new[]{ "ObjectType" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Mruv.Objects.UpdateObjectModelResponse), global::Mruv.Objects.UpdateObjectModelResponse.Parser, null, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Mruv.Objects.DeleteObjectModelRequest), global::Mruv.Objects.DeleteObjectModelRequest.Parser, new[]{ "Model" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Mruv.Objects.DeleteObjectModelResponse), global::Mruv.Objects.DeleteObjectModelResponse.Parser, null, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Mruv.Objects.FetchAllModelsRequest), global::Mruv.Objects.FetchAllModelsRequest.Parser, new[]{ "ChunkSize" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Mruv.Objects.FetchAllModelsResponse), global::Mruv.Objects.FetchAllModelsResponse.Parser, new[]{ "Models" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, })
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// SA-MP Object type data structure.
  /// </summary>
  public sealed partial class ObjectModel : pb::IMessage<ObjectModel>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ObjectModel> _parser = new pb::MessageParser<ObjectModel>(() => new ObjectModel());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ObjectModel> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Mruv.Objects.ModelsReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ObjectModel() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ObjectModel(ObjectModel other) : this() {
      model_ = other.model_;
      modelName_ = other.modelName_;
      name_ = other.name_;
      category_ = other.category_;
      length_ = other.length_;
      width_ = other.width_;
      height_ = other.height_;
      size_ = other.size_;
      tags_ = other.tags_.Clone();
      hasCollision_ = other.hasCollision_;
      breaksOnHit_ = other.breaksOnHit_;
      hasAnimation_ = other.hasAnimation_;
      visibleByTime_ = other.visibleByTime_;
      visibleFrom_ = other.visibleFrom_;
      visibleTo_ = other.visibleTo_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ObjectModel Clone() {
      return new ObjectModel(this);
    }

    /// <summary>Field number for the "model" field.</summary>
    public const int ModelFieldNumber = 1;
    private int model_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Model {
      get { return model_; }
      set {
        model_ = value;
      }
    }

    /// <summary>Field number for the "model_name" field.</summary>
    public const int ModelNameFieldNumber = 2;
    private string modelName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ModelName {
      get { return modelName_; }
      set {
        modelName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 3;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "category" field.</summary>
    public const int CategoryFieldNumber = 4;
    private string category_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Category {
      get { return category_; }
      set {
        category_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "length" field.</summary>
    public const int LengthFieldNumber = 5;
    private double length_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public double Length {
      get { return length_; }
      set {
        length_ = value;
      }
    }

    /// <summary>Field number for the "width" field.</summary>
    public const int WidthFieldNumber = 6;
    private double width_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public double Width {
      get { return width_; }
      set {
        width_ = value;
      }
    }

    /// <summary>Field number for the "height" field.</summary>
    public const int HeightFieldNumber = 7;
    private double height_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public double Height {
      get { return height_; }
      set {
        height_ = value;
      }
    }

    /// <summary>Field number for the "size" field.</summary>
    public const int SizeFieldNumber = 8;
    private double size_;
    /// <summary>
    /// if no size specified, it will be calculated based on length, width and height
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public double Size {
      get { return size_; }
      set {
        size_ = value;
      }
    }

    /// <summary>Field number for the "tags" field.</summary>
    public const int TagsFieldNumber = 9;
    private static readonly pb::FieldCodec<string> _repeated_tags_codec
        = pb::FieldCodec.ForString(74);
    private readonly pbc::RepeatedField<string> tags_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> Tags {
      get { return tags_; }
    }

    /// <summary>Field number for the "has_collision" field.</summary>
    public const int HasCollisionFieldNumber = 10;
    private bool hasCollision_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasCollision {
      get { return hasCollision_; }
      set {
        hasCollision_ = value;
      }
    }

    /// <summary>Field number for the "breaks_on_hit" field.</summary>
    public const int BreaksOnHitFieldNumber = 11;
    private bool breaksOnHit_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool BreaksOnHit {
      get { return breaksOnHit_; }
      set {
        breaksOnHit_ = value;
      }
    }

    /// <summary>Field number for the "has_animation" field.</summary>
    public const int HasAnimationFieldNumber = 12;
    private bool hasAnimation_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasAnimation {
      get { return hasAnimation_; }
      set {
        hasAnimation_ = value;
      }
    }

    /// <summary>Field number for the "visible_by_time" field.</summary>
    public const int VisibleByTimeFieldNumber = 16;
    private bool visibleByTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool VisibleByTime {
      get { return visibleByTime_; }
      set {
        visibleByTime_ = value;
      }
    }

    /// <summary>Field number for the "visible_from" field.</summary>
    public const int VisibleFromFieldNumber = 17;
    private uint visibleFrom_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint VisibleFrom {
      get { return visibleFrom_; }
      set {
        visibleFrom_ = value;
      }
    }

    /// <summary>Field number for the "visible_to" field.</summary>
    public const int VisibleToFieldNumber = 18;
    private uint visibleTo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint VisibleTo {
      get { return visibleTo_; }
      set {
        visibleTo_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ObjectModel);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ObjectModel other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Model != other.Model) return false;
      if (ModelName != other.ModelName) return false;
      if (Name != other.Name) return false;
      if (Category != other.Category) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Length, other.Length)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Width, other.Width)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Height, other.Height)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Size, other.Size)) return false;
      if(!tags_.Equals(other.tags_)) return false;
      if (HasCollision != other.HasCollision) return false;
      if (BreaksOnHit != other.BreaksOnHit) return false;
      if (HasAnimation != other.HasAnimation) return false;
      if (VisibleByTime != other.VisibleByTime) return false;
      if (VisibleFrom != other.VisibleFrom) return false;
      if (VisibleTo != other.VisibleTo) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Model != 0) hash ^= Model.GetHashCode();
      if (ModelName.Length != 0) hash ^= ModelName.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Category.Length != 0) hash ^= Category.GetHashCode();
      if (Length != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Length);
      if (Width != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Width);
      if (Height != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Height);
      if (Size != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Size);
      hash ^= tags_.GetHashCode();
      if (HasCollision != false) hash ^= HasCollision.GetHashCode();
      if (BreaksOnHit != false) hash ^= BreaksOnHit.GetHashCode();
      if (HasAnimation != false) hash ^= HasAnimation.GetHashCode();
      if (VisibleByTime != false) hash ^= VisibleByTime.GetHashCode();
      if (VisibleFrom != 0) hash ^= VisibleFrom.GetHashCode();
      if (VisibleTo != 0) hash ^= VisibleTo.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Model != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Model);
      }
      if (ModelName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ModelName);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Name);
      }
      if (Category.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Category);
      }
      if (Length != 0D) {
        output.WriteRawTag(41);
        output.WriteDouble(Length);
      }
      if (Width != 0D) {
        output.WriteRawTag(49);
        output.WriteDouble(Width);
      }
      if (Height != 0D) {
        output.WriteRawTag(57);
        output.WriteDouble(Height);
      }
      if (Size != 0D) {
        output.WriteRawTag(65);
        output.WriteDouble(Size);
      }
      tags_.WriteTo(output, _repeated_tags_codec);
      if (HasCollision != false) {
        output.WriteRawTag(80);
        output.WriteBool(HasCollision);
      }
      if (BreaksOnHit != false) {
        output.WriteRawTag(88);
        output.WriteBool(BreaksOnHit);
      }
      if (HasAnimation != false) {
        output.WriteRawTag(96);
        output.WriteBool(HasAnimation);
      }
      if (VisibleByTime != false) {
        output.WriteRawTag(128, 1);
        output.WriteBool(VisibleByTime);
      }
      if (VisibleFrom != 0) {
        output.WriteRawTag(136, 1);
        output.WriteUInt32(VisibleFrom);
      }
      if (VisibleTo != 0) {
        output.WriteRawTag(144, 1);
        output.WriteUInt32(VisibleTo);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Model != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Model);
      }
      if (ModelName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ModelName);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Name);
      }
      if (Category.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Category);
      }
      if (Length != 0D) {
        output.WriteRawTag(41);
        output.WriteDouble(Length);
      }
      if (Width != 0D) {
        output.WriteRawTag(49);
        output.WriteDouble(Width);
      }
      if (Height != 0D) {
        output.WriteRawTag(57);
        output.WriteDouble(Height);
      }
      if (Size != 0D) {
        output.WriteRawTag(65);
        output.WriteDouble(Size);
      }
      tags_.WriteTo(ref output, _repeated_tags_codec);
      if (HasCollision != false) {
        output.WriteRawTag(80);
        output.WriteBool(HasCollision);
      }
      if (BreaksOnHit != false) {
        output.WriteRawTag(88);
        output.WriteBool(BreaksOnHit);
      }
      if (HasAnimation != false) {
        output.WriteRawTag(96);
        output.WriteBool(HasAnimation);
      }
      if (VisibleByTime != false) {
        output.WriteRawTag(128, 1);
        output.WriteBool(VisibleByTime);
      }
      if (VisibleFrom != 0) {
        output.WriteRawTag(136, 1);
        output.WriteUInt32(VisibleFrom);
      }
      if (VisibleTo != 0) {
        output.WriteRawTag(144, 1);
        output.WriteUInt32(VisibleTo);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Model != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Model);
      }
      if (ModelName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ModelName);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Category.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Category);
      }
      if (Length != 0D) {
        size += 1 + 8;
      }
      if (Width != 0D) {
        size += 1 + 8;
      }
      if (Height != 0D) {
        size += 1 + 8;
      }
      if (Size != 0D) {
        size += 1 + 8;
      }
      size += tags_.CalculateSize(_repeated_tags_codec);
      if (HasCollision != false) {
        size += 1 + 1;
      }
      if (BreaksOnHit != false) {
        size += 1 + 1;
      }
      if (HasAnimation != false) {
        size += 1 + 1;
      }
      if (VisibleByTime != false) {
        size += 2 + 1;
      }
      if (VisibleFrom != 0) {
        size += 2 + pb::CodedOutputStream.ComputeUInt32Size(VisibleFrom);
      }
      if (VisibleTo != 0) {
        size += 2 + pb::CodedOutputStream.ComputeUInt32Size(VisibleTo);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ObjectModel other) {
      if (other == null) {
        return;
      }
      if (other.Model != 0) {
        Model = other.Model;
      }
      if (other.ModelName.Length != 0) {
        ModelName = other.ModelName;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Category.Length != 0) {
        Category = other.Category;
      }
      if (other.Length != 0D) {
        Length = other.Length;
      }
      if (other.Width != 0D) {
        Width = other.Width;
      }
      if (other.Height != 0D) {
        Height = other.Height;
      }
      if (other.Size != 0D) {
        Size = other.Size;
      }
      tags_.Add(other.tags_);
      if (other.HasCollision != false) {
        HasCollision = other.HasCollision;
      }
      if (other.BreaksOnHit != false) {
        BreaksOnHit = other.BreaksOnHit;
      }
      if (other.HasAnimation != false) {
        HasAnimation = other.HasAnimation;
      }
      if (other.VisibleByTime != false) {
        VisibleByTime = other.VisibleByTime;
      }
      if (other.VisibleFrom != 0) {
        VisibleFrom = other.VisibleFrom;
      }
      if (other.VisibleTo != 0) {
        VisibleTo = other.VisibleTo;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Model = input.ReadInt32();
            break;
          }
          case 18: {
            ModelName = input.ReadString();
            break;
          }
          case 26: {
            Name = input.ReadString();
            break;
          }
          case 34: {
            Category = input.ReadString();
            break;
          }
          case 41: {
            Length = input.ReadDouble();
            break;
          }
          case 49: {
            Width = input.ReadDouble();
            break;
          }
          case 57: {
            Height = input.ReadDouble();
            break;
          }
          case 65: {
            Size = input.ReadDouble();
            break;
          }
          case 74: {
            tags_.AddEntriesFrom(input, _repeated_tags_codec);
            break;
          }
          case 80: {
            HasCollision = input.ReadBool();
            break;
          }
          case 88: {
            BreaksOnHit = input.ReadBool();
            break;
          }
          case 96: {
            HasAnimation = input.ReadBool();
            break;
          }
          case 128: {
            VisibleByTime = input.ReadBool();
            break;
          }
          case 136: {
            VisibleFrom = input.ReadUInt32();
            break;
          }
          case 144: {
            VisibleTo = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Model = input.ReadInt32();
            break;
          }
          case 18: {
            ModelName = input.ReadString();
            break;
          }
          case 26: {
            Name = input.ReadString();
            break;
          }
          case 34: {
            Category = input.ReadString();
            break;
          }
          case 41: {
            Length = input.ReadDouble();
            break;
          }
          case 49: {
            Width = input.ReadDouble();
            break;
          }
          case 57: {
            Height = input.ReadDouble();
            break;
          }
          case 65: {
            Size = input.ReadDouble();
            break;
          }
          case 74: {
            tags_.AddEntriesFrom(ref input, _repeated_tags_codec);
            break;
          }
          case 80: {
            HasCollision = input.ReadBool();
            break;
          }
          case 88: {
            BreaksOnHit = input.ReadBool();
            break;
          }
          case 96: {
            HasAnimation = input.ReadBool();
            break;
          }
          case 128: {
            VisibleByTime = input.ReadBool();
            break;
          }
          case 136: {
            VisibleFrom = input.ReadUInt32();
            break;
          }
          case 144: {
            VisibleTo = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// Request message for rpc `CreateObjectModel`.
  /// </summary>
  public sealed partial class CreateObjectModelRequest : pb::IMessage<CreateObjectModelRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CreateObjectModelRequest> _parser = new pb::MessageParser<CreateObjectModelRequest>(() => new CreateObjectModelRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CreateObjectModelRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Mruv.Objects.ModelsReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CreateObjectModelRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CreateObjectModelRequest(CreateObjectModelRequest other) : this() {
      objectType_ = other.objectType_ != null ? other.objectType_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CreateObjectModelRequest Clone() {
      return new CreateObjectModelRequest(this);
    }

    /// <summary>Field number for the "object_type" field.</summary>
    public const int ObjectTypeFieldNumber = 1;
    private global::Mruv.Objects.ObjectModel objectType_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Mruv.Objects.ObjectModel ObjectType {
      get { return objectType_; }
      set {
        objectType_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CreateObjectModelRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CreateObjectModelRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(ObjectType, other.ObjectType)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (objectType_ != null) hash ^= ObjectType.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (objectType_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(ObjectType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (objectType_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(ObjectType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (objectType_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ObjectType);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CreateObjectModelRequest other) {
      if (other == null) {
        return;
      }
      if (other.objectType_ != null) {
        if (objectType_ == null) {
          ObjectType = new global::Mruv.Objects.ObjectModel();
        }
        ObjectType.MergeFrom(other.ObjectType);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (objectType_ == null) {
              ObjectType = new global::Mruv.Objects.ObjectModel();
            }
            input.ReadMessage(ObjectType);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (objectType_ == null) {
              ObjectType = new global::Mruv.Objects.ObjectModel();
            }
            input.ReadMessage(ObjectType);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// Response message for rpc `CreateObjectModel`.
  /// </summary>
  public sealed partial class CreateObjectModelResponse : pb::IMessage<CreateObjectModelResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CreateObjectModelResponse> _parser = new pb::MessageParser<CreateObjectModelResponse>(() => new CreateObjectModelResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CreateObjectModelResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Mruv.Objects.ModelsReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CreateObjectModelResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CreateObjectModelResponse(CreateObjectModelResponse other) : this() {
      id_ = other.id_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CreateObjectModelResponse Clone() {
      return new CreateObjectModelResponse(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private uint id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CreateObjectModelResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CreateObjectModelResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Id);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Id);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Id);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CreateObjectModelResponse other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// Request message for rpc `GetObjectModel`.
  /// </summary>
  public sealed partial class GetObjectModelRequest : pb::IMessage<GetObjectModelRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GetObjectModelRequest> _parser = new pb::MessageParser<GetObjectModelRequest>(() => new GetObjectModelRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetObjectModelRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Mruv.Objects.ModelsReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetObjectModelRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetObjectModelRequest(GetObjectModelRequest other) : this() {
      model_ = other.model_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetObjectModelRequest Clone() {
      return new GetObjectModelRequest(this);
    }

    /// <summary>Field number for the "model" field.</summary>
    public const int ModelFieldNumber = 1;
    private int model_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Model {
      get { return model_; }
      set {
        model_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetObjectModelRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetObjectModelRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Model != other.Model) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Model != 0) hash ^= Model.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Model != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Model);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Model != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Model);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Model != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Model);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetObjectModelRequest other) {
      if (other == null) {
        return;
      }
      if (other.Model != 0) {
        Model = other.Model;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Model = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Model = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// Response message for rpc `GetObjectModel`.
  /// </summary>
  public sealed partial class GetObjectModelResponse : pb::IMessage<GetObjectModelResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GetObjectModelResponse> _parser = new pb::MessageParser<GetObjectModelResponse>(() => new GetObjectModelResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetObjectModelResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Mruv.Objects.ModelsReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetObjectModelResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetObjectModelResponse(GetObjectModelResponse other) : this() {
      objectType_ = other.objectType_ != null ? other.objectType_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetObjectModelResponse Clone() {
      return new GetObjectModelResponse(this);
    }

    /// <summary>Field number for the "object_type" field.</summary>
    public const int ObjectTypeFieldNumber = 1;
    private global::Mruv.Objects.ObjectModel objectType_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Mruv.Objects.ObjectModel ObjectType {
      get { return objectType_; }
      set {
        objectType_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetObjectModelResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetObjectModelResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(ObjectType, other.ObjectType)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (objectType_ != null) hash ^= ObjectType.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (objectType_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(ObjectType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (objectType_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(ObjectType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (objectType_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ObjectType);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetObjectModelResponse other) {
      if (other == null) {
        return;
      }
      if (other.objectType_ != null) {
        if (objectType_ == null) {
          ObjectType = new global::Mruv.Objects.ObjectModel();
        }
        ObjectType.MergeFrom(other.ObjectType);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (objectType_ == null) {
              ObjectType = new global::Mruv.Objects.ObjectModel();
            }
            input.ReadMessage(ObjectType);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (objectType_ == null) {
              ObjectType = new global::Mruv.Objects.ObjectModel();
            }
            input.ReadMessage(ObjectType);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// Request message for rpc `UpdateObjectModel`.
  /// </summary>
  public sealed partial class UpdateObjectModelRequest : pb::IMessage<UpdateObjectModelRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<UpdateObjectModelRequest> _parser = new pb::MessageParser<UpdateObjectModelRequest>(() => new UpdateObjectModelRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<UpdateObjectModelRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Mruv.Objects.ModelsReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UpdateObjectModelRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UpdateObjectModelRequest(UpdateObjectModelRequest other) : this() {
      objectType_ = other.objectType_ != null ? other.objectType_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UpdateObjectModelRequest Clone() {
      return new UpdateObjectModelRequest(this);
    }

    /// <summary>Field number for the "object_type" field.</summary>
    public const int ObjectTypeFieldNumber = 1;
    private global::Mruv.Objects.ObjectModel objectType_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Mruv.Objects.ObjectModel ObjectType {
      get { return objectType_; }
      set {
        objectType_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as UpdateObjectModelRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(UpdateObjectModelRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(ObjectType, other.ObjectType)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (objectType_ != null) hash ^= ObjectType.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (objectType_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(ObjectType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (objectType_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(ObjectType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (objectType_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ObjectType);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(UpdateObjectModelRequest other) {
      if (other == null) {
        return;
      }
      if (other.objectType_ != null) {
        if (objectType_ == null) {
          ObjectType = new global::Mruv.Objects.ObjectModel();
        }
        ObjectType.MergeFrom(other.ObjectType);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (objectType_ == null) {
              ObjectType = new global::Mruv.Objects.ObjectModel();
            }
            input.ReadMessage(ObjectType);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (objectType_ == null) {
              ObjectType = new global::Mruv.Objects.ObjectModel();
            }
            input.ReadMessage(ObjectType);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// Response message for rpc `UpdateObjectModel`.
  /// </summary>
  public sealed partial class UpdateObjectModelResponse : pb::IMessage<UpdateObjectModelResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<UpdateObjectModelResponse> _parser = new pb::MessageParser<UpdateObjectModelResponse>(() => new UpdateObjectModelResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<UpdateObjectModelResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Mruv.Objects.ModelsReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UpdateObjectModelResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UpdateObjectModelResponse(UpdateObjectModelResponse other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UpdateObjectModelResponse Clone() {
      return new UpdateObjectModelResponse(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as UpdateObjectModelResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(UpdateObjectModelResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(UpdateObjectModelResponse other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
        }
      }
    }
    #endif

  }

  /// <summary>
  /// Request message for rpc `DeleteObjectModel`.
  /// </summary>
  public sealed partial class DeleteObjectModelRequest : pb::IMessage<DeleteObjectModelRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<DeleteObjectModelRequest> _parser = new pb::MessageParser<DeleteObjectModelRequest>(() => new DeleteObjectModelRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<DeleteObjectModelRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Mruv.Objects.ModelsReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DeleteObjectModelRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DeleteObjectModelRequest(DeleteObjectModelRequest other) : this() {
      model_ = other.model_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DeleteObjectModelRequest Clone() {
      return new DeleteObjectModelRequest(this);
    }

    /// <summary>Field number for the "model" field.</summary>
    public const int ModelFieldNumber = 1;
    private int model_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Model {
      get { return model_; }
      set {
        model_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as DeleteObjectModelRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(DeleteObjectModelRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Model != other.Model) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Model != 0) hash ^= Model.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Model != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Model);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Model != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Model);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Model != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Model);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(DeleteObjectModelRequest other) {
      if (other == null) {
        return;
      }
      if (other.Model != 0) {
        Model = other.Model;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Model = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Model = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// Response message for rpc `DeleteObjectModel`.
  /// </summary>
  public sealed partial class DeleteObjectModelResponse : pb::IMessage<DeleteObjectModelResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<DeleteObjectModelResponse> _parser = new pb::MessageParser<DeleteObjectModelResponse>(() => new DeleteObjectModelResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<DeleteObjectModelResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Mruv.Objects.ModelsReflection.Descriptor.MessageTypes[8]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DeleteObjectModelResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DeleteObjectModelResponse(DeleteObjectModelResponse other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DeleteObjectModelResponse Clone() {
      return new DeleteObjectModelResponse(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as DeleteObjectModelResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(DeleteObjectModelResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(DeleteObjectModelResponse other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
        }
      }
    }
    #endif

  }

  /// <summary>
  /// Request message for rpc `FetchAll`.
  /// </summary>
  public sealed partial class FetchAllModelsRequest : pb::IMessage<FetchAllModelsRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<FetchAllModelsRequest> _parser = new pb::MessageParser<FetchAllModelsRequest>(() => new FetchAllModelsRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<FetchAllModelsRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Mruv.Objects.ModelsReflection.Descriptor.MessageTypes[9]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FetchAllModelsRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FetchAllModelsRequest(FetchAllModelsRequest other) : this() {
      chunkSize_ = other.chunkSize_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FetchAllModelsRequest Clone() {
      return new FetchAllModelsRequest(this);
    }

    /// <summary>Field number for the "chunk_size" field.</summary>
    public const int ChunkSizeFieldNumber = 1;
    private uint chunkSize_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint ChunkSize {
      get { return chunkSize_; }
      set {
        chunkSize_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as FetchAllModelsRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(FetchAllModelsRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ChunkSize != other.ChunkSize) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ChunkSize != 0) hash ^= ChunkSize.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ChunkSize != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(ChunkSize);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ChunkSize != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(ChunkSize);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ChunkSize != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ChunkSize);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(FetchAllModelsRequest other) {
      if (other == null) {
        return;
      }
      if (other.ChunkSize != 0) {
        ChunkSize = other.ChunkSize;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ChunkSize = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ChunkSize = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// Response message for rpc `FetchAll`.
  /// </summary>
  public sealed partial class FetchAllModelsResponse : pb::IMessage<FetchAllModelsResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<FetchAllModelsResponse> _parser = new pb::MessageParser<FetchAllModelsResponse>(() => new FetchAllModelsResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<FetchAllModelsResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Mruv.Objects.ModelsReflection.Descriptor.MessageTypes[10]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FetchAllModelsResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FetchAllModelsResponse(FetchAllModelsResponse other) : this() {
      models_ = other.models_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FetchAllModelsResponse Clone() {
      return new FetchAllModelsResponse(this);
    }

    /// <summary>Field number for the "models" field.</summary>
    public const int ModelsFieldNumber = 1;
    private static readonly pbc::MapField<int, global::Mruv.Objects.ObjectModel>.Codec _map_models_codec
        = new pbc::MapField<int, global::Mruv.Objects.ObjectModel>.Codec(pb::FieldCodec.ForInt32(8, 0), pb::FieldCodec.ForMessage(18, global::Mruv.Objects.ObjectModel.Parser), 10);
    private readonly pbc::MapField<int, global::Mruv.Objects.ObjectModel> models_ = new pbc::MapField<int, global::Mruv.Objects.ObjectModel>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<int, global::Mruv.Objects.ObjectModel> Models {
      get { return models_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as FetchAllModelsResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(FetchAllModelsResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!Models.Equals(other.Models)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= Models.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      models_.WriteTo(output, _map_models_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      models_.WriteTo(ref output, _map_models_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += models_.CalculateSize(_map_models_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(FetchAllModelsResponse other) {
      if (other == null) {
        return;
      }
      models_.Add(other.models_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            models_.AddEntriesFrom(input, _map_models_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            models_.AddEntriesFrom(ref input, _map_models_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
