name: .NET Core

on: 
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.402
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Create nuget package
      run: dotnet pack -p:PackageVersion=$(git describe --tags --abbrev=0 | sed -r 's/v(.*)-(.*)-(.*)/\1 /')
    - name: Add nuget sources
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: nuget source Add -Name "GitHub" -Source "https://nuget.pkg.github.com/MruV-RP/index.json" -UserName MruV-RP -Password $GITHUB_TOKEN
    - name: Publish nuget to nuget.org
      env: 
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      run: dotnet nuget push bin/Debug/*.nupkg -k $NUGET_API_KEY -s https://api.nuget.org/v3/index.json
    - name: Publish nuget to github packages
      run: dotnet nuget push bin/Debug/*.nupkg -s "GitHub"
