name: .NET Core

on: 
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.402
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Create nuget package
      run: dotnet pack -p:PackageVersion=$(git describe --tags --abbrev=0 | sed -r 's/v(.*)-(.*)-(.*)/\1 /')

    - name: Publish nuget to github packages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: dotnet nuget push bin/Debug/*.nupkg -k $NUGET_API_KEY -s https://nuget.pkg.github.com/MruV-RP/index.json
